---
title: "Homework 6"
author: "Angelica Bailey"
date: "2025-11-26"
output: github_document
---

```{r}
library(tidyverse)
library(broom)
```


## Problem 1

Reading in data
```{r}
homicide_data = read_csv("data/homicide-data.csv")
```

Data cleaning
```{r}
homicide_data = homicide_data |> 
  #creating city_state variable and binary variable for solved/unsolved homicides
  mutate(city_state = str_c(city, ", ", state), 
         homicide_solved = if_else(disposition == "Closed by arrest", 1, 0)    
         ) |> 
  #filtering states and race
  filter(!city_state %in% c("Dallas, TX",
                            "Phoenix, AZ",
                            "Kansas City, MO",
                            "Tulsa, AL"),
         victim_race %in% c("White", "Black")) |> 
  #victim age as numeric
  mutate(victim_age = suppressWarnings(as.numeric(victim_age)))
```


Fitting logistic regression for Baltimore, MD
```{r}
baltimore_data = homicide_data |> 
  filter(city_state == "Baltimore, MD")

baltimore_fit = glm(
  homicide_solved ~ victim_age + victim_sex + victim_race,
  data = baltimore_data,
  family = binomial(link = "logit")
)

# tidy model with adjusted odds ratio
tidy_fit = tidy(baltimore_fit, exponentiate = TRUE, conf.int = TRUE)

#extracting OR for victim sex
tidy_fit |> 
  filter(term == "victim_sexMale")
```


Iterating for all cities
```{r, warning=FALSE}
city_or_results = homicide_data |> 
  group_by(city_state) |> 
  nest() |> 
  #fitting logistic model for each city
  mutate(
    model = map(data, ~ glm(
      homicide_solved ~ victim_age + victim_sex + victim_race,
      data = .x,
      family = binomial
    )),
    #extracting OR
    results = map(model, ~ tidy(
      .x,
      exponentiate = TRUE,
      conf.int = TRUE
    ))
  ) |> 
  unnest(results) |> 
  filter(term == "victim_sexMale") |> 
  select(city_state, estimate, conf.low, conf.high)
```


Creating plot
```{r}
city_or_results = city_or_results |> 
  #reordering cities by OR
  mutate(city_state = fct_reorder(city_state, estimate))

ggplot(city_or_results, 
       aes(x = estimate, 
           y = city_state)) +
  geom_point(color = "darkgreen") +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), color = "darkseagreen4", height = 0.2) +
  geom_vline(xintercept = 1, linetype = "dashed") +
  labs(
    title = "Adjusted Odds Ratios for Solving Homicides (Male vs Female Victims)",
    x = "Odds Ratio (Male vs Female)",
    y = "City"
  ) +
  theme_minimal(base_size = 12)
```



